export const ADD_PHONE = "ADD_PHONE";
export const ADD_PHONE_SUCCESS = "ADD_PHONE_SUCCESS";
export const ADD_PHONE_FAILED = "ADD_PHONE_FAILED";

export const GET_PHONE = "GET_PHONE";
export const GET_PHONE_SUCCESS = "GET_PHONE_SUCCESS";
export const GET_PHONE_FAILED = "GET_PHONE_FAILED";

export const GET_ALL_PHONES = "GET_ALL_PHONES";
export const GET_ALL_PHONES_SUCCESS = "GET_ALL_PHONES_SUCCESS";
export const GET_ALL_PHONES_FAILED = "GET_ALL_PHONES_FAILED";

export const EDIT_PHONE = "EDIT_PHONE";
export const EDIT_PHONE_SUCCESS = "EDIT_PHONE_SUCCESS";
export const EDIT_PHONE_FAILED = "EDIT_PHONE_FAILED";
